import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif, Nanum_Pen_Script } from "next/font/google";
import "./globals.css";
import { DotPattern } from "@/components/ui/dot-pattern";
import { AnimatedThemeToggler } from "@/components/ui/animated-theme-toggler";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nanumPenScript = Nanum_Pen_Script({
  variable: "--font-nanum-pen-script",
  subsets: ["latin"],
  weight: "400",
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Navbar } from "@/components/ui/navbar";
import Oneko from "@/components/ui/oneko";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nanumPenScript.variable} ${instrumentSerif.variable} antialiased`}
      >
        <Navbar />
        <Oneko />
        <AnimatedThemeToggler className="absolute top-4 right-4 z-[60]" />
        <DotPattern className="opacity-30 -z-10" />
        {children}
      </body>
    </html>
  );
}
